### ISSUE TITLE
Why teach the comma console.log syntax instead of just backticks?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-basics-intro-to-debugging-readme#1]
The comma syntax was nice when we didn't have backticks but now I feel like this line `console.log("In getPrice(), 'selection' contains:", selection);` is more simply `console.log(`In getPrice() 'selection' contains: #{selection}`). 

It also means we don't have to teach them a new syntax

**Comment by gj** [comment]
I mean, it's just passing a series of arguments to a method, which they already know.

Not sure that
```js
console.log(`In getPrice(), 'selection' contains: ${selection}`);
```

is any simpler than
```js
console.log("In getPrice(), 'selection' contains:", selection);
```

**Comment by Lukeghenco** [comment]
Going to have to agree with @gj on this one. I've not seen anyone use the `${}` syntax often with console.log.
