### ISSUE TITLE
Gif is wrong

### ISSUE THREAD

**Issue by chalt0319** [learn-co-curriculum/js-basics-intro-to-debugging-readme#10]
I think the gif that you are using from 30 Rock that says "Wheres my mac n' cheese" is not what she says in the episode. Please see this link: (https://www.imdb.com/title/tt1001578/plotsummary) where it says "Where's my sandwich". I could be wrong, but I wanted to bring it to someones attention.

**Comment by sgharms** [comment]
@chalt0319 

After consulting with resident Flatiron School "30 Rock" guru, Jess, she provided this video link:

https://www.youtube.com/watch?v=PbSI4tqYIsM&t=0m5s

In "Sandwich Day" Liz certainly asks where her sandwich is (see end of clip), and menaces poor Kenneth with an Emmy.

**However**, note the presence of Josh in the M&C version (who is _not_ in the "Sandwich Day" version). I believe this gif is taken from a different arc.

We appreciate your validating the veracity of this clip.

Yours, 

Flatiron Curriculum 💙
