### ISSUE TITLE
console.table example

### ISSUE THREAD

**Issue by wley3337** [learn-co-curriculum/js-basics-intro-to-debugging-readme#13]
The example given is for an object {mother:{firstName: "First name", lastName: "Last name", etc....} rather than an array. Is is possible to add both images side by side and add in the text `object` s and `array` s and either give examples of each or just the array= [4, 5, 6]?

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#15. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
