### ISSUE TITLE
Suggestion: Add instructions for debugging in a local environment

### ISSUE THREAD

**Issue by kodyclemens** [learn-co-curriculum/js-basics-intro-to-debugging-readme#14]
It would be very helpful to have instructions showing students how to debug in a local environment. One big hurdle from Ruby to JS for me was the lack of Pry to inspect what was happening during runtime. I didn't figure out how to debug on my machine until I got to the Daily Lunch lab. :confounded:

Using `mocha.run();` to manually run tests in the console is not easy to figure out unless you ask a cohort lead or know that the tests are using Mocha (in which case you probably already know how to debug!). On the flip side, for the tests that run automatically and open a browser window, it was not immediately clear that I could open the console to debug after adding in a debugger.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#15. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
