### ISSUE TITLE
Have an opinion on which console function to use

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-basics-intro-to-debugging-readme#2]
I generally just tell folks that until much later in their careers, `console.log` is sufficient

**Comment by gj** [comment]
This is already in there:
>You probably won't use `console.error()` very often — `console.log()` is by far the best tool for simple debugging — but now at least you'll know what's happening when you open up the JS console on a random site and see a bunch of bright red warnings.

But also added another reminder:
>At this stage of your programming career, `console.log()` is really the only tool you need for debugging with the `console` object. However, you'll probably encounter the following two `console` methods, `error()` and `warn()`, in the wild.
