### ISSUE TITLE
console.warn()

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/js-basics-intro-to-debugging-readme#4]
"The warn() method is often used to alert developers looking at the JS console that they've done something inadvisable but not reaching the level of a full-blown error. For example, we could highlight the usage of a soon-to-be-deprecated feature:

`console.**log**("Hmmm, you probably don't want to do that...");`

> Looks like the intention was to use console.warn not console.log 

// WARN: Hmmm, you probably don't want to do that...

When we use console.warn() in code snippets, we'll preface the output statements with WARN: to differentiate them from other logged message"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Ary770.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
