### ISSUE TITLE
Type to be fixed: 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-basics-intro-to-debugging-readme#7]
TYPORGRAPHICAL NOTE: When we use console.log() in code snippets, we'll preface the output statements with LOG:, such as in the above example. This is to differentiate messages logged out to the console from values returned by an expression, which are represented with =>, e.g.:

should be Typographical

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
