### ISSUE TITLE
var => let ? 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-basics-intro-to-debugging-readme#8]
Previous lessons told us we should pretty much not use var -- perhaps this should be let? 

var number = 10;
 
function addTwoNumbers(a, b){
  a + b;
}
 
function multiplyByTwo(n) {
  number * 2;
}
 
console.log(multiplyByTwo(addTwoNumbers(1,3))); //=> undefined(?!)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
