### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by DontJar** [learn-co-curriculum/js-basics-intro-to-debugging-readme#9]
There is a small typo in the second sentence following the section header "Demonstrate console.warn()".  
The text reads:
   > It provides step between a regular log() message and a more dire error() message.

I think there is a word missing after "provides", and it should say
  > It provides **a** step between a regular log() message and a more dire error() message.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @DontJar.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
